# Generated by Django 4.2.11 on 2026-06-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_operacion_tipopropiedad_propiedad_operacion_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad')),
            ],
        ),
    ]
