# Generated by Django 4.2.11 on 2026-06-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_visita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
    ]
