# Generated by Django 4.2.11 on 2026-06-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_operacion_tipopropiedad_propiedad_operacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacion',
            options={'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='tipopropiedad',
            options={'verbose_name': 'Tipo de Propiedad', 'verbose_name_plural': 'Tipos de Propiedades'},
        ),
    ]
